### ISSUE TITLE
include saliva sample IDs in QR code

### ISSUE THREAD

**Issue by richrobe** [mad-lab-fau/carwatch-app#14]
It would be good to have the saliva sample IDs (S1, S2, ..., SA) also somewhere present in the logs. either as extra in the "study_metadata" action I proposed in #13, or as individual extras when barcodes were scanned (in addition to the "internal" saliva_id which is always 0, 1, ...

This makes it easier to match the "internal" saliva sample IDs with the "user-facing" IDs when parsing the log data with the `carwatch` python package.

**Comment by a-mosquito** [comment]
fixed in #18
